baseURL = 'https://synergy-screen.example.com'
languageCode = 'en-us'
title = 'Synergy Screen - Drug Combination Visualization'
theme = 'basic'

[params]
  description = "Interactive visualization for drug combination synergy screen data"
  author = "Arnaud Amzallag"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[server]
  [[server.headers]]
    for = "/**"
    [server.headers.values]
      Access-Control-Allow-Origin = "*"
      Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'"
