baseURL = 'https://arnaudmgh.github.io/synergy-screen'
languageCode = 'en-us'
title = 'Synergy Screen - Drug Combination Visualization'

# Ignore files and directories that shouldn't trigger rebuilds
ignoreFiles = [
  "static/data/.*",
  "static_preprocessing/.*",
  "node_modules/.*",
  "\\.tmp$",
  "\\.log$"
]

[params]
  description = "Interactive visualization for drug combination synergy screen data"
  author = "Arnaud Amzallag"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[server]
  [[server.headers]]
    for = "/**"
    [server.headers.values]
      Access-Control-Allow-Origin = "*"
      Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'"
